### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by darin-ellis7** [darin-ellis7/GridGame#1]
- [x] Obtain necessary sprites

- [x] Create grid system

- [x] Allow Character movement on grid

- [x]  Character sprite animation state machine (even an initial combinatorial FSM will suffice)
